In [1]:
import pandas as pd 
import numpy as np

In [6]:
app_ema = pd.read_csv("../../syntheticData/csv_export/app_ema.csv")
app_heartratesample = pd.read_csv("../../syntheticData/csv_export/app_heartratesample.csv")
app_stresssample = pd.read_csv("../../syntheticData/csv_export/app_stresssample.csv")
app_user = pd.read_csv("../../syntheticData/csv_export/app_user.csv")
app_wearabledevice = pd.read_csv("../../syntheticData/csv_export/app_wearabledevice.csv")

In [7]:
app_ema.head(5)

,user_id,timestamp,status,mood,energy,stress,physical_activity,weight_lbs,notes
0,306,2026-06-01 00:00:00,answered,4.0,NaN,NaN,NaN,NaN,NaN
1,306,2026-06-01 00:01:00,answered,3.0,NaN,NaN,NaN,NaN,NaN
2,306,2026-06-01 00:02:00,answered,2.0,NaN,NaN,NaN,NaN,NaN
3,306,2026-06-01 00:03:00,answered,3.0,NaN,NaN,NaN,NaN,NaN
4,306,2026-06-01 00:04:00,missed,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
app_heartratesample.head()

   device_id            timestamp  bpm  zone  hrv_rmssd         source
0        306  2026-06-01 00:00:00   76   NaN      74.00  Garmin Venu 3
1        306  2026-06-01 00:30:00   73   NaN      76.37  Garmin Venu 3
2        306  2026-06-01 01:00:00   74   NaN      77.71  Garmin Venu 3
3        306  2026-06-01 01:30:00   72   NaN      82.62  Garmin Venu 3
4        306  2026-06-01 02:00:00   73   NaN      74.14  Garmin Venu 3

In [10]:
app_stresssample.head()

   device_id            timestamp  stress_score         source
0        306  2026-06-01 00:00:00            24  Garmin Venu 3
1        306  2026-06-01 00:30:00            13  Garmin Venu 3
2        306  2026-06-01 01:00:00            17  Garmin Venu 3
3        306  2026-06-01 01:30:00            15  Garmin Venu 3
4        306  2026-06-01 02:00:00            28  Garmin Venu 3

In [11]:
app_user.head()

,email,first_name,last_name,birthdate,gender,height_feet,height_inches,goal_weight,goal_to_lose_weight,goal_to_feel_better,password
0,75a7da96-a5ea-411f-8be9-d5185d09d3b3@synthetic...,Hayden,Lee,2007-12-03,female,5,10,175.8,True,False,NaN
1,4cbc513a-0df8-454d-b4c4-173bd9dd8bf1@synthetic...,Hayden,Patel,2004-01-17,other,5,1,156.0,True,False,NaN
2,fc2fa878-0d43-49a4-b866-a7a14a696b12@synthetic...,Rowan,Martinez,2003-10-09,other,5,5,138.2,True,True,NaN
3,75bcc917-2133-4729-a79f-47e0bafa5468@synthetic...,Elliot,Brown,2003-04-24,female,4,9,148.4,False,False,NaN
4,e0cc6392-3695-4e2c-ba5d-03773f0bbc1a@synthetic...,Hayden,Kim,2004-05-23,male,5,5,123.5,True,False,NaN

In [12]:
app_wearabledevice.head()

,user_id,fitbit_device_id,device_type,device_name,last_synced_at,is_active,created_at
0,306,garmin-75a7da96,smartwatch,Garmin Venu 3,2026-06-11,True,2026-06-11
1,307,garmin-4cbc513a,smartwatch,Garmin Vivoactive 5,2026-06-11,True,2026-06-11
2,308,garmin-fc2fa878,smartwatch,Garmin Vivoactive 5,2026-06-11,True,2026-06-11
3,309,garmin-75bcc917,smartwatch,Garmin Venu 3,2026-06-11,True,2026-06-11
4,310,garmin-e0cc6392,smartwatch,Garmin Vivoactive 6,2026-06-11,True,2026-06-11