In [1]:
import pandas as pd 
import numpy as np

In [ ]:
app_ema = pd.read_csv("../../syntheticData/csv_export/app_ema.csv")
app_heartratesample = pd.read_csv("../../syntheticData/csv_export/app_heartratesample.csv")
app_user = pd.read_csv("../../syntheticData/csv_export/app_user.csv")
app_wearabledevice = pd.read_csv("../../syntheticData/csv_export/app_wearabledevice.csv")

In [3]:
app_ema.head(5)

,user_id,timestamp,mood,energy,stress,physical_activity,weight_lbs,notes
0,221,2026-06-01 00:00:00,4,NaN,NaN,NaN,NaN,NaN
1,221,2026-06-01 00:01:00,3,NaN,NaN,NaN,NaN,NaN
2,221,2026-06-01 00:02:00,2,NaN,NaN,NaN,NaN,NaN
3,221,2026-06-01 00:03:00,3,NaN,NaN,NaN,NaN,NaN
4,221,2026-06-01 00:04:00,3,NaN,NaN,NaN,NaN,NaN

In [4]:
app_heartratesample.head()

   device_id            timestamp  bpm          zone
0        221  2026-06-01 00:00:00   76  out_of_range
1        221  2026-06-01 00:05:00   74  out_of_range
2        221  2026-06-01 00:10:00   74  out_of_range
3        221  2026-06-01 00:15:00   72  out_of_range
4        221  2026-06-01 00:20:00   77  out_of_range

In [5]:
app_user.head()

,email,first_name,last_name,birthdate,gender,height_feet,height_inches,goal_weight,goal_to_lose_weight,goal_to_feel_better,password
0,1f734bfc-497a-47e6-b61c-ed0c7977ce90@synthetic...,Hayden,Lee,2007-12-03,female,5,10,175.8,True,False,NaN
1,c2369beb-f364-4aea-9f61-9e52a7953d49@synthetic...,Hayden,Patel,2004-01-17,other,5,1,156.0,True,False,NaN
2,05d7ac7f-38cb-4f70-8471-6c97e689583b@synthetic...,Rowan,Martinez,2003-10-09,other,5,5,138.2,True,True,NaN
3,5bbcc143-5efe-47fb-94cb-8ef98463a1d0@synthetic...,Elliot,Brown,2003-04-24,female,4,9,148.4,False,False,NaN
4,8a88bdab-a4ef-4917-a172-b599e9b3a65d@synthetic...,Hayden,Kim,2004-05-23,male,5,5,123.5,True,False,NaN

In [6]:
app_wearabledevice.head()

,user_id,fitbit_device_id,device_type,device_name,last_synced_at,is_active,created_at
0,221,garmin-1f734bfc,smartwatch,Garmin Venu 3,2026-06-11,True,2026-06-11
1,222,garmin-c2369beb,smartwatch,Garmin Vivoactive 6,2026-06-11,True,2026-06-11
2,223,garmin-05d7ac7f,smartwatch,Garmin Vivoactive 5,2026-06-11,True,2026-06-11
3,224,garmin-5bbcc143,smartwatch,Garmin Venu 3,2026-06-11,True,2026-06-11
4,225,garmin-8a88bdab,smartwatch,Garmin Vivoactive 5,2026-06-11,True,2026-06-11